# Generated by Django 3.1.7 on 2021-03-20 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('phenomenon', '0004_navbaritems'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NavbarItems',
            new_name='NavbarItem',
        ),
    ]
